### ISSUE TITLE
Found new iot tools

### ISSUE THREAD

**Issue by ManuCart** [HQarroum/awesome-iot#10]
https://github.com/home-assistant/home-assistant

**Comment by HQarroum** [comment]
Hey, thank you for pointing that great project out !

Would it be possible for you to fill up a proper pull request for its integration ?

Thanks! 😄

**Comment by aabowen** [comment]
I just created a PR adding Home Assistant. #16

**Comment by HQarroum** [comment]
PR has been merged, thanks again.
