### ISSUE TITLE
Add PJON?

### ISSUE THREAD

**Issue by gioblu** [HQarroum/awesome-iot#28]
CIao @HQarroum , compliments for the really instructive and nice repo. Shouldnt PJON be added too?

**Comment by HQarroum** [comment]
Didn't know about PJON, seems to be addressing a real need which could be employed in the IoT. However it spans over multiple categories of this Wiki in my opinion, and cannot be thought as a simple protocol. I am wondering if the categories are well disposed to include this kind of project.
What do you think?

**Comment by gioblu** [comment]
Ciao @HQarroum, thank you for your response and compliments for the nice and informative work. 

PJON proposes:
- A data-link or physical layer specification (and its implementation) for wired [PJDL](https://github.com/gioblu/PJON/blob/master/strategies/SoftwareBitBang/specification/PJDL-specification-v1.0.md) and wireless (with radio or infrared / visible light) applications 
- A network protocol specification (and its implementation) on top: [PJON](https://github.com/gioblu/PJON/blob/master/specification/PJON-protocol-specification-v1.0.md)
- And also being the implementation able to support other data-links, like Serial, TCP and UDP and many different devices / architectures, could be considered a framework!

I would suggest you to consider the addition of also wired data-links because in many cases IOT is not necessarily implemented wirelessly. With this I mean RS485 (vastly used), CAN, LIN, potentially 1-wire and so on.

**Comment by HQarroum** [comment]
Finally added PJON as a network protocol as commit https://github.com/HQarroum/awesome-iot/commit/72adad370b9f9d31cd6504ccc4c92657558ee3af. Thanks for the issue, and sorry for addressing it so late!
