### ISSUE TITLE
How-to article about AWS Timestream - The new Time Series database from AWS to work with IoT products.

### ISSUE THREAD

**Issue by RichardSilveira** [HQarroum/awesome-iot#68]
Hi, let me know if this addition makes sense for you:
https://itnext.io/how-to-begin-with-the-amazon-timestream-in-5-simple-steps-19c129040d9c

This time series is awesome and help a lot who is new in this field, I wrote an article to help who is starting on this world, also who would like to test this new AWS managed time-series database

AWS Timestream is a time-series database to collect IoT data over-time.

**Comment by HQarroum** [comment]
Hi @RichardSilveira, thanks for the addition, it would make sense to add it. Would you be able to propose a PR ?

**Comment by RichardSilveira** [comment]
Yes, I'll for sure, thank's.
