### ISSUE TITLE
Adding Raspberry pi Pico

### ISSUE THREAD

**Issue by KeshavAnandBhagat** [HQarroum/awesome-iot#88]
I want to add **Raspberry pi Pico** 
Please assign me this issue

**Comment by KeshavAnandBhagat** [comment]
Respected 
@HQarroum
Raspberry pi Pico is latest micro controller. 
I want to add content for that. 
Please assign me this issue, so that I can proceed further

**Comment by HQarroum** [comment]
Alright, would you be to open a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) to add the Raspberry Pi Pico in the right section ?
